### ISSUE TITLE
Integration tests fails with SecurityException: Security error

### ISSUE THREAD

**Issue by johlju** [dsccommunity/DscResource.Test#38]
When `Restore-TestEnvironment` is called at the end of an integration tests it fails with the error in Azure DevOps.

```
2019-12-27T10:17:05.5277355Z   [-] Error occurred in test script 'D:\a\1\s\tests\Integration\MSFT_WebApplicationHandler.Integration.Tests.ps1' 0ms
2019-12-27T10:17:05.5277528Z     SecurityException: Security error.
2019-12-27T10:17:05.5277606Z     at Restore-TestEnvironment, D:\a\1\s\output\RequiredModules\DscResource.Test\0.8.0\DscResource.Test.psm1: line 1628
```

The line this happens on is 
```powershell
    if ($script:MachineOldExecutionPolicy)
    {
        Set-ExecutionPolicy -ExecutionPolicy $script:MachineOldExecutionPolicy -Scope LocalMachine -Force -ErrorAction Stop
    }
```

**Comment by johlju** [comment]
In the build worker in Azure DevOps (2016 image) the execution policy for the machine is `'RemoteSigned'` which is changed to `'Unrestricted'` when `Initialize-TestEnvironment`. So apparently there are an issue reverting the execution policy when `Restore-TestEnvironment` is called.

**Comment by gaelcolas** [comment]
Have you tried an integration tests that does nothing besides Initialize and Restore?
I think it may not be an issue with the Execution Policy, but with the fact that the environment has changed if you kicked off some DSC config locally, conflicting with setting the Execution Policy back... (config precedence, current user changes in privileges...)

Getting the full error message of the issue would be best, as it should tell you if the `SecurityException` is because of Access Denied (account changes) or precedence (change in local policy? or other scope)

**Comment by johlju** [comment]
How do we get the full error message?

_I am not running integration tests locally._

**Comment by gaelcolas** [comment]
In this case you could try a Set-ExecutionPolicy directly, outside the Describe block at the end (after removing the failing `Restore-TestEnvironment`).
It should still fail but giving you more details about the error (because it's not wrapped within pester).

**Comment by johlju** [comment]
But the Restore-TestEnvironment function is already running outside of any Describe-block.

**Comment by johlju** [comment]
I fixed the integration test to be a simpler one but still generates the error if the code in PR #39 is not used.
